// File generated by Antigravity based on provided Firebase config files.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

import 'config/env.dart';

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static FirebaseOptions get android {
    switch (Env.current) {
      case Environment.dev:
        return const FirebaseOptions(
          apiKey: 'AIzaSyD4Hkckj3TbjhhS9S5sf9RmTvvc82p7vdo',
          appId: '1:901444143218:android:288993a14c036d48149aeb',
          messagingSenderId: '901444143218',
          projectId: 'biege-app',
          storageBucket: 'biege-app.firebasestorage.app',
        );
      case Environment.prod:
        return const FirebaseOptions(
          apiKey: 'AIzaSyBxcOml39s0y3rNliQqkBJ5qcjeBLL6wFA',
          appId: '1:628292955928:android:4d5a7ca1be34e6754d786d',
          messagingSenderId: '628292955928',
          projectId: 'biege-app-live',
          storageBucket: 'biege-app-live.firebasestorage.app',
        );
    }
  }

  static FirebaseOptions get ios {
    switch (Env.current) {
      case Environment.dev:
        return const FirebaseOptions(
          apiKey: 'AIzaSyCB8Mw5LE37XYVZslZmTMn8q6ehHlk8mJ8',
          appId: '1:901444143218:ios:3b6feb6b8d9c863b149aeb',
          messagingSenderId: '901444143218',
          projectId: 'biege-app',
          storageBucket: 'biege-app.firebasestorage.app',
          iosBundleId: 'com.app.beige.dev',
        );
      case Environment.prod:
        return const FirebaseOptions(
          apiKey: 'AIzaSyA8pk8VuMI2yyBkjSj0fDXYsERMhPcTqQ8',
          appId: '1:628292955928:ios:47f65bbb7644b4864d786d',
          messagingSenderId: '628292955928',
          projectId: 'biege-app-live',
          storageBucket: 'biege-app-live.firebasestorage.app',
          iosBundleId: 'com.app.beige',
        );
    }
  }
}
