import 'dart:io';
import 'navigation_helper.dart';

/// Collects [NavResult] entries across all test cases and
/// writes a formatted Markdown table to [outputPath].
class ReportBuilder {
  final String outputPath;
  final List<_RouteEntry> _entries = [];
  DateTime? _sessionStart;

  ReportBuilder({this.outputPath = 'navigation_report.md'});

  void startSession() {
    _sessionStart = DateTime.now();
    _entries.clear();
  }

  /// Call this from each test case to register a route result.
  void record({
    required String route,
    required String routeName,
    NavResult? loadResult,
    NavResult? guardResult,
    NavResult? deepLinkResult,
    NavResult? backNavResult,
  }) {
    _entries.add(
      _RouteEntry(
        route: route,
        routeName: routeName,
        loadResult: loadResult,
        guardResult: guardResult,
        deepLinkResult: deepLinkResult,
        backNavResult: backNavResult,
      ),
    );
  }

  /// Writes the final `navigation_report.md` to [outputPath].
  Future<void> writeReport() async {
    final buffer = StringBuffer();
    final now = DateTime.now();
    final duration = _sessionStart != null
        ? now.difference(_sessionStart!).inSeconds
        : 0;

    final total = _entries.length;
    final passed = _entries.where((e) => e.overallStatus == '✅ PASS').length;
    final failed = total - passed;

    // ── Header ──────────────────────────────────────────────
    buffer.writeln('# Navigation Test Report');
    buffer.writeln();
    buffer.writeln('**Generated:** ${now.toIso8601String()}');
    buffer.writeln('**Duration:** ${duration}s');
    buffer.writeln(
      '**Total Routes:** $total | **Passed:** $passed | **Failed:** $failed',
    );
    buffer.writeln();

    // ── Summary badges ──────────────────────────────────────
    if (failed == 0) {
      buffer.writeln('> 🟢 All navigation checks passed.');
    } else {
      buffer.writeln('> 🔴 $failed route(s) failed — see details below.');
    }
    buffer.writeln();

    // ── Main table ──────────────────────────────────────────
    buffer.writeln('## Results');
    buffer.writeln();
    buffer.writeln(
      '| # | Route Name | Path | Load | Auth Guard | Deep Link | Back Nav | Status |',
    );
    buffer.writeln(
      '|---|-----------|------|------|-----------|----------|---------|--------|',
    );

    for (var i = 0; i < _entries.length; i++) {
      final e = _entries[i];
      buffer.writeln(
        '| ${i + 1} '
        '| `${e.routeName}` '
        '| `${e.route}` '
        '| ${_cell(e.loadResult)} '
        '| ${_cell(e.guardResult)} '
        '| ${_cell(e.deepLinkResult)} '
        '| ${_cell(e.backNavResult)} '
        '| ${e.overallStatus} |',
      );
    }

    buffer.writeln();

    // ── Failures detail ──────────────────────────────────────
    final failures = _entries
        .where((e) => e.overallStatus != '✅ PASS')
        .toList();
    if (failures.isNotEmpty) {
      buffer.writeln('## Failure Details');
      buffer.writeln();
      for (final e in failures) {
        buffer.writeln('### `${e.routeName}` — `${e.route}`');
        buffer.writeln();
        _appendFailureDetail(buffer, 'Load', e.loadResult);
        _appendFailureDetail(buffer, 'Auth Guard', e.guardResult);
        _appendFailureDetail(buffer, 'Deep Link', e.deepLinkResult);
        _appendFailureDetail(buffer, 'Back Nav', e.backNavResult);
        buffer.writeln();
      }
    }

    // ── Route coverage section ───────────────────────────────
    buffer.writeln('## Route Coverage');
    buffer.writeln();
    buffer.writeln('| Check Type | Covered | Total | Coverage |');
    buffer.writeln('|-----------|---------|-------|---------|');

    final checks = ['load', 'guard', 'deepLink', 'backNav'];
    final labels = ['Screen Load', 'Auth Guard', 'Deep Link', 'Back Nav'];

    for (var i = 0; i < checks.length; i++) {
      final covered = _entries.where((e) => _hasCheck(e, checks[i])).length;
      final pct = total > 0
          ? ((covered / total) * 100).toStringAsFixed(0)
          : '0';
      buffer.writeln('| ${labels[i]} | $covered | $total | $pct% |');
    }

    buffer.writeln();
    buffer.writeln('---');
    buffer.writeln('*Generated by Beige Navigation Test Tool*');

    // ── Write file ───────────────────────────────────────────
    final file = File(outputPath);
    await file.writeAsString(buffer.toString());
    // ignore: avoid_print
    print('\n📋 Navigation report written to: ${file.absolute.path}\n');
  }

  String _cell(NavResult? result) {
    if (result == null) return '—';
    return result.passed ? '✅' : '❌';
  }

  bool _hasCheck(_RouteEntry e, String type) {
    switch (type) {
      case 'load':
        return e.loadResult != null;
      case 'guard':
        return e.guardResult != null;
      case 'deepLink':
        return e.deepLinkResult != null;
      case 'backNav':
        return e.backNavResult != null;
      default:
        return false;
    }
  }

  void _appendFailureDetail(
    StringBuffer buffer,
    String label,
    NavResult? result,
  ) {
    if (result != null && !result.passed) {
      buffer.writeln('- **$label:** ❌ `${result.error ?? "unknown error"}`');
    }
  }
}

class _RouteEntry {
  final String route;
  final String routeName;
  final NavResult? loadResult;
  final NavResult? guardResult;
  final NavResult? deepLinkResult;
  final NavResult? backNavResult;

  _RouteEntry({
    required this.route,
    required this.routeName,
    this.loadResult,
    this.guardResult,
    this.deepLinkResult,
    this.backNavResult,
  });

  String get overallStatus {
    final results = [
      loadResult,
      guardResult,
      deepLinkResult,
      backNavResult,
    ].where((r) => r != null).cast<NavResult>();
    if (results.isEmpty) return '⚠️ SKIP';
    return results.every((r) => r.passed) ? '✅ PASS' : '❌ FAIL';
  }
}
